### ISSUE TITLE
Installation not working

### ISSUE THREAD

**Issue by NityaNagaSai** [csc510fall23g45/slash#10]
pip3 install -r requirements.txt command is not working. Build Error.

**Comment by Anish7-anish** [comment]
I have checked requirements.txt file and some dependency versions are deprecated. I will update the versions.

**Comment by sairajzero** [comment]
I have updated the versions for dependencies in requirements.txt file.  #1  [cd31629](https://github.com/csc510fall23g45/slash/commit/cd3162928314c35e0ff26e4fb4716845b6910923)
