### ISSUE TITLE
Multiple User Wishlist Issue

### ISSUE THREAD

**Issue by NityaNagaSai** [csc510fall23g45/slash#11]
When there are multiple users and they are trying to access the Wishlists, it only uses one Wishlist for all users.

**Comment by sairajzero** [comment]
The existing version of Slash uses the same file path for adding the wishlists, we will need to store them separately

**Comment by Anish7-anish** [comment]
Each User should have a seperate database for wishlist.

**Comment by sairajzero** [comment]
I have added support for multi-users in [here](https://github.com/csc510fall23g45/slash/commit/4d6cf230d1d4ee8c382480a255dee2e85b23d11a). The data files are stored in separate file paths for each username so that each user can have their own set of wishlists and wishlisted items
