### ISSUE TITLE
Etsy No of Ratings Scraper Issue

### ISSUE THREAD

**Issue by mahathii** [csc510fall23g45/slash#6]
For the products from Etsy, values for number of ratings are not visible.

**Comment by Anish7-anish** [comment]
The Etsy website when given some value to the query, the element-id is getting changed and we have to check properly which page is required getting the element-id for scraping results.

**Comment by Anish7-anish** [comment]
I checked the scraper file and the website and fixed the issue by changing them to correct element-ids. 
You can check the changes [Here](https://github.com/csc510fall23g45/slash/commit/ca389d090fb9596d69af6705e6348b2955119b3e)
