### ISSUE TITLE
Walmart prices are not displaying correctly

### ISSUE THREAD

**Issue by mahathii** [csc510fall23g45/slash#7]
Walmart price values has unwanted strings in the results.

**Comment by NityaNagaSai** [comment]
Check the format function in formatter.py file and correct it as required to remove the string.

**Comment by NityaNagaSai** [comment]
You can check the changes [Here](https://github.com/csc510fall23g45/slash/commit/422c0979da68854d96c81f617efd7255afeec5c8)
