### ISSUE TITLE
some walmart prices have 2 decimal dots

### ISSUE THREAD

**Issue by sairajzero** [csc510fall23g45/slash#8]
Some price string values returned by Walmart formatter have 2 decimal dots

**Comment by NityaNagaSai** [comment]
The regular expressions added in the formatter function have to be checked once and we have to make the required changes to close the issue.

**Comment by NityaNagaSai** [comment]
The required changes are made. You can check the changes [here](https://github.com/csc510fall23g45/slash/commit/e56054d40b09c8daa1cfeff4d678049fb0516bf9)
