### ISSUE TITLE
Filtering feature

### ISSUE THREAD

**Issue by sairajzero** [csc510fall23g45/slash#9]
There are no filtering options available in the existing slash, we need to add filters based on product feature such as prices

**Comment by NityaNagaSai** [comment]
We should add filters with min price , min ratings and max price. The required text elements should be added in the front-end.

**Comment by mahathii** [comment]
Filters with min price, max price and min ratings are added. You can check the changes [Here](https://github.com/csc510fall23g45/slash/commit/07b46e74a69a7e582b5c7cb0a1cecf53a28ea844)
